### ISSUE TITLE
Is it possible to support LuaJIT?

### ISSUE THREAD

**Issue by tommyettinger** [meric/l2l#1]
I'm wondering what features of Lua 5.2 are needed by l2l.  LuaJIT supports a subset of the 5.2 features, including goto and labels, but I am unsure what would need to be changed in l2l to be backwards compatible with LuaJIT's 5.??? extensions.  I will try my hand at this, but it is unlikely I will do too well.  Maybe Moonscript (also here on GitHub, https://github.com/leafo/moonscript ) could serve as some example code for how to compile to Lua 5.1 and thus retain compatibility with standard Lua and LuaJIT.
As an aside, this is a pretty cool project and I wish it had gotten some more attention in the community when it was new.  A compiler/translator that fits in one, probably-less-than-1000-SLoC file is not something you see every day...

**Comment by meric** [comment]
l2l rewritten to support both Lua 5.3 and LuaJIT.
