### ISSUE TITLE
Add Makefile, linting, tests, samples

### ISSUE THREAD

**Issue by meric** [meric/l2l#17]
Regression errors have been cropping up after bug fixes, perhaps it would be a good idea to add a Makefile that can run samples, add some rudimentary unit tests, run some linting, e.g. (https://github.com/mpeterv/luacheck).

**Comment by technomancy** [comment]
I've got a stash where I work on making the code a bit more luacheck-friendly. Are you OK with a patch that gets rid of all the "unused variable" and "unused initial value" warnings? We can invoke luacheck with some args to disable some of its warnings.

I think the best way to start would just be to supply it with a whitelist of globals (`_R _C _D symbol`) for the time being until we get a chance to get rid of all the globals and leave on all the other warnings.

**Comment by technomancy** [comment]
Here's what I've got so far: https://github.com/technomancy/l2l/tree/makefile

I need to give it a bit more manual testing before merging.

**Comment by technomancy** [comment]
I've added some tests to the branch above, but two of them are still failing. One of them (the last one) might be a faulty test, but I'm pretty sure the other one (`list.lsp`) is indicative of a bug in l2l:

```lisp
(let (a 5 b 9 c 51)
  (list a (cons b c)))
```
> lua: ./compiler.lua:655: ./itertools.lua:166: bad argument #1 to 'maxn' (table expected, got number)

https://github.com/technomancy/l2l/blob/makefile/tests/init.lua#L19

**Comment by meric** [comment]
Yes it definitely is a bug in `l2l`, specifically the `itertools` module.
```
list = require("itertools").list
cons = require("itertools").cons

list(a, cons(b, c))
```

Looking at it now.

**Comment by meric** [comment]
Perhaps it's because the `(list)` function doesn't take varargs. it's currently written to take a single argument, which has to be a vector (plain lua array). i.e. `(list (vector 1 2 3 4 5))` I realise it differs to existing lisp implementations, I must have been thinking too much python when I wrote it.

**Comment by technomancy** [comment]
I see. Maybe `to_list` or `array->list` would be a better name?

**Comment by meric** [comment]
`list` is the prototype or class that instantiates the list. Since varargs, `...` in lua is limited to maximum length of 255 or 256, I thought it'd be safer to make the constructor take a table instead. But now it breaks lisp conventions... perhaps the class should be renamed and we add a function `list` that takes varargs? Thoughts?

**Comment by technomancy** [comment]
I don't necessarily advocate for slavish adherence to tradition, but as far as I know `list` works the same way in every other lisp out there, and it would be very surprising for people coming from other dialects to have it work differently here.

**Comment by meric** [comment]
Making a new issue for `list`.

**Comment by meric** [comment]
Looks like `(a . b)` isn't implemented yet...

**Comment by meric** [comment]
@technomancy Should the `tests/list.lsp` be corrected to the following?

```
(let (a 5 b 9 c 51)
  (cons a (cons b c)))
```

otherwise, a cadr on (list a (cons b c)) returns (cons b c) as I would have thought.

sbcl:

```
0[8] (car (cdr (list 1 (cons 2 3))))

(2 . 3)
```

**Comment by technomancy** [comment]
Quite right; I've fixed it. Unfortunately calling `tostring` on an improper list causes a crash, but I left that out of the assertion message and got this to pass. Turns out replacing the dotted notation with `cons` in the Y combinator implementation allowed this to pass, so I think we should be good to merge now.

**Comment by meric** [comment]
This commit a1b6bd90ecccc73e2f97cb1f0b9cad0f3b75a1f1 should fix the `tostring` issue.

**Comment by meric** [comment]
Alright merged!
