### ISSUE TITLE
Question: 5.1 compatibility

### ISSUE THREAD

**Issue by technomancy** [meric/l2l#3]
I'm quite interested in this project; unfortunately I was thinking of using it with a [love2d](http://love2d.org) game, which tragically uses LuaJIT compiled *without* `-DLUAJIT_ENABLE_LUA52COMPAT`.

Out of curiosity, what kinds of things prevent the codebase from being compatible with 5.1?

**Comment by tst2005** [comment]
I take a look,
l2l does not use _ENV
l2l use only two `load()` of lua 5.2

I think l2l should be used on Lua 5.1 with [compat_env](https://github.com/davidm/lua-compat-env)

Regards,

**Comment by meric** [comment]
@technomancy Thanks for the suggestion. @tst2005 Thanks for the tip!

Give it a go, it should work with Lua 5.1 now, I've given a cursory and not extensive check. 

See 266661cc2e7d3e5adf738360d2d7fa2dba4f7842

**Comment by technomancy** [comment]
Thanks a bunch! I will see about integrating this into my game soon.

**Comment by technomancy** [comment]
Great work; this was easy to (integrate into my game)[https://gitlab.com/technomancy/bussard/blob/master/os/lisp/init.lua] Thanks!
