### ISSUE TITLE
compile_if tries to unpack nil when missing else branch

### ISSUE THREAD

**Issue by technomancy** [meric/l2l#37]
Inside `compile_if`, we create `ref` and assign the last value of each branch to it. However, when we have a "possibly-variadic" value, we assign a table to the ref and then unpack it after the `if`. This is fine as long as we have an `else` branch, but if we don't then the `ref` never gets set, but we attempt to unpack it.

I have a feeling this whole thing could be a lot simpler if we could just identify tail positions and insert `return` calls directly instead of tracking things with `_var0` and such, but maybe this is more difficult than it sounds. It would certainly result in dramatically more readable compiler output.

**Comment by meric** [comment]
See #36.
`If` is currently not implemented.
In the meantime, for conditional statements, you could escape into Lua then write the if statement.

Something like (not tested):
```
(fn x (y)
  \if z then z() end
  y)
```

**Comment by technomancy** [comment]
Is this the correct fix for the problem? I will submit a PR if so: https://gitlab.com/technomancy/l2love/commit/6f3993d222789ddaf944de070805f8e944b02e62

**Comment by technomancy** [comment]
Oh sorry; wrote my reply before I saw yours.

**Comment by technomancy** [comment]
OK; sounds like this is not really relevant any more; thanks.
