### ISSUE TITLE
Sandboxing

### ISSUE THREAD

**Issue by technomancy** [meric/l2l#4]
It looks like the entire Lua environment is available to any lisp code to run. Is there any way to limit this just to a specific sandbox? I can see in the `compiler.eval` function that there's a way to pass in your own `env` table, but how difficult would it be to limit it to *only* what's in env?

I could take a swing at implementing this if you point me in the right direction; I've implemented a Scheme before.

**Comment by tst2005** [comment]
Take a look at my sandbox "[see also](https://github.com/tst2005/lua-isolation#see-also)" section.
I hope it helps you.

**Comment by technomancy** [comment]
I'm not sure I understand; none of those sandbox links mention lisp. Are you saying I can run the entire `repl` function itself inside a typical Lua sandbox, and that will protect the code running inside it? It seems like that would be problematic; the repl needs access to the `io` table, which I want to prevent user code from seeing.

**Comment by technomancy** [comment]
Wait, I may have misunderstood you. Were you saying that you could use the techniques in the link to achieve sandboxing with l2l as it currently stands, or were you trying to explain how you would add sandboxing to l2l?

If it's the latter, I should clarify that I was asking for hints of how it would work in the l2l codebase itself. I'm quite familiar with Lua sandboxing in general; I just don't know enough about the codebase to know where to dig in.

**Comment by meric** [comment]
I think it could work if you run l2l in an environment where io only has one function, that is, io.tmpfile().

I used the io file interface as a crutch - it was designed for writing files but it was also convenient for a parser to use to move forwards and backwards, and select the next N bytes. Now it's very ingrained into the code.

Actually what I've been working on is working out an interface to replace it. It's slow, exploratory ~~work~~ fun at the moment.

**Comment by technomancy** [comment]
> I used the io file interface as a crutch - it was designed for writing files but it was also convenient for a parser to use to move forwards and backwards, and select the next N bytes. Now it's very ingrained into the code.

Would it help to use stringio instead of io.tmpfile?

  https://github.com/stevedonovan/Penlight/blob/master/lua/pl/stringio.lua

Upon further reflection I don't think sandboxing the repl function
itself would help; it's probably the compiler.eval that would need to be
changed since that's where the call to load happens. Sandboxing
compiler.eval wouldn't work because the sandbox would have to contain
setmetatable for the eval function to work, and if the setmetatable
function is exposed to the sandbox, you can use it to break out of the
sandbox.

Since you're specifically passing _G into load, I think it would be
necessary to take another arg. Right now it seems the env table is
additive, whereas what we really need is two tables; one for things to
add to the environment, and one for a table to replace _G as the
whole environment.

Does that make sense? I think I can play around with this and try to
patch it myself now that I've tracked it down to this particular load
call in compiler.eval.

**Comment by meric** [comment]
Yes, it looks like stringio would do! Yeah it looks like it can be as easy
as adding an extra "G" argument to eval that defaults to _G.

**Comment by technomancy** [comment]
> Yeah it looks like it can be as easy as adding an extra "G" argument to eval that defaults to _G.

Unfortunately it's not quite that simple. This is what I get when I try
to take _G out of the call to load:

       lua: [string "_C[hash("chunk")]=function (block, stream, ..."]:16: attempt to call global '_46_46' (a nil value)
       stack traceback:
       	[string "_C[hash("chunk")]=function (block, stream, ..."]:16: in function '?'
       	./compiler.lua:125: in function 'compile'
       	./compiler.lua:452: in function 'defun'
       	./compiler.lua:473: in function '?'
       	./compiler.lua:125: in function 'compile'
       	./compiler.lua:583: in function 'eval'
       	./compiler.lua:811: in main chunk
       	[C]: in function 'require'
       	./l2l:7: in main chunk
       	[C]: ?

Not really sure what that identifier refers to. I thought perhaps there
was a global defined in the compile function, and that the globals
needed to be preserved between compile and load calls, but this appears
not to be the case.

**Comment by meric** [comment]
In compiler.lua, there's a section that's written in lisp, when it's using
itself to bootstrap up.

Each form relies on using the same _C, and _G, and any code that's compiled
further will be missing utilities that's defined in that section unless
they also share the same _C and _G.

Here is the diff of what I need to do to get the l2l prompt to show up.

```

gd compiler.lua | tee

diff --git a/compiler.lua b/compiler.lua

index de2e26a..1d41015 100644

--- a/compiler.lua

+++ b/compiler.lua

@@ -21,6 +21,8 @@ local pack = itertools.pack

local show = itertools.show

local raise = exception.raise


local _C



-- Keyword table. All symbols that match those in this table will be
compiled

-- down into Lua as a symbol that is valid in Lua. Uniquess probable but not

@@ -553,7 +555,8 @@ end


local compiler


eval = function (obj, stream, env)env, G)

  G = G or _G

  -- Include the following into the `core` library. The `core` library is

  -- automatically imported into _G in all compiled programs.

  -- See `compiler.build`.

@@ -584,7 +587,7 @@ eval = function (obj, stream, env)



  local code = table.concat(block, "\n") .. "\nreturn ".. reference

  local f, err = load(code, code, nil, setmetatable(env or {},

      {__newindex=_G,{__newindex=G, __index = setmetatable(core,
{__index=_G})})){__index=G})}))

  if f then

    local objs, count = pack(pcall(f))

    local ok = table.remove(objs, 1)

@@ -805,13 +808,24 @@ compiler = {



local ok, form


local G = {

  table = table,

  print = print,

  tostring = tostring,

  type = type,

  getmetatable = getmetatable,


}


repeat

  ok, obj = pcall(reader.read, stream)

  if ok then

    eval(obj, stream, {

      assign = assign,

      declare = declare

    })declare,

      _C = _C,

    }, G)

  end

until not ok


@@ -819,4 +833,4 @@ if getmetatable(obj) ~= reader.EOFException then

  error(obj)

end


return compiler

```

**Comment by meric** [comment]
Hmm let's see how this goes.

**Comment by meric** [comment]
Checkout sample06.

**Comment by technomancy** [comment]
I got this working great in the latest commit of my game: https://gitlab.com/technomancy/bussard/commit/848ceb95ea96ee46b92c42370e8e53c5adbbfd66

Thanks!
