### ISSUE TITLE
Suggestion: Rename #import to @import

### ISSUE THREAD

**Issue by meric** [meric/l2l#42]
Maybe it might be a good idea to rename #import to @import, to free up the # symbol to be used as the length operator, to match Lua.

Right now the length operator in lisp is implemented as "length", which is different to Lua's "#".

I note that escaping into Lua, to use #,`(print \#myarray)` currently works.

**Comment by technomancy** [comment]
So the idea here is that it's a compiler directive or something, and that is why it gets special syntactic sugar? Is this different from a macro call somehow?

I'm personally of the opinion that we should start with the expanded version of each form and add the syntactic sugar after the dust settles a bit so we can see which constructs need a shorthand for.

**Comment by meric** [comment]
"#" is the read dispatch macro, and "import" is one of the registered dispatches..http://clhs.lisp.se/Body/f_set__1.htm Like what I understand of Common Lisp's, but instead of a single sub-character, I allowed symbols. So this proposal will change the dispatch character from "#" to "@", so that "#" can be freed up to write a "length" read macro.

`#import` is not a special syntax. The special syntax we do currently have is:

`(:byte text 1)` == `text:byte(1)` and `(.byte string)` == `string.byte`.

**Comment by meric** [comment]
Hmm, 12 hours later, I think it's possible to write the expanded form.

By wrapping this in a special form.
```
local mod = import_extension(invariant, name)
    load_extension(invariant, mod, alias)
```

What should it be called? Extend?

```
(extend fn)
```

**Comment by technomancy** [comment]
I'm not sure what it does, so I can't really provide input on a name.

But I understand why you would use special syntax for *read-time* directives; I thought it was used for compile-time instead.
