### ISSUE TITLE
LuaJIT support

### ISSUE THREAD

**Issue by technomancy** [meric/l2l#44]
I've found 3 problems preventing running on LuaJIT so far:

* Missing `table.pack`; easy fix
* `vector:insert` has an undefined field `self.n`; not sure why
* `function missing parameters or body`; stack trace below

```
ERROR in test_local():
	[string "local lua = require("l2l.lua")..."]:15: function missing parameters or body
stack traceback:
	[string "local lua = require("l2l.lua")..."]:15: in function 'statize'
	./l2l/compiler.lua:157: in function 'statize'
	./l2l/compiler.lua:400: in function 'compile'
	./l2l/compiler.lua:504: in function 'compile_or_cached'
	./l2l/compiler.lua:327: in function 'build'
	./l2l/compiler.lua:339: in function 'import'
	./l2l/reader.lua:324: in function 'import_extension'
	./l2l/compiler.lua:392: in function 'compile'
	l2l/test.lua:9: in function 'assert_exec_equal'
	l2l/test.lua:17: in function <l2l/test.lua:16>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:202: in main chunk
	[C]: at 0x00404d50
```

Is this due to the fact that Lua 5.1 (and LuaJIT by default) does not support iterators from metatables, or do you think there is a different root cause?

**Comment by meric** [comment]
```
Is this due to the fact that Lua 5.1 (and LuaJIT by default) does not support iterators from metatables, or do you think there is a different root cause?
```

It definitely requires iterators from metatables.

LuaJIT would require to be compiled with 5.2 extensions to work.

**Comment by technomancy** [comment]
OK, good to know. How do you want to proceed in supporting regular LuaJIT then? Should we write our own metatable-aware `pairs` and `ipairs` and take care to use those instead of the stock ones?

**Comment by meric** [comment]
That's a good idea. I was thinking about it, maybe it could be called "iterate". Do you have a suggestion for a name? When __ipairs is supported, iterate == ipairs, otherwise iterate will be our own implementation.

**Comment by technomancy** [comment]
I just came across this library: https://github.com/keplerproject/lua-compat-5.2

It means a runtime dependency on luarocks though.

This library can be used in two ways: one only affects one file at a time, while the other makes global changes. Also it fixes a lot more than just the iterators, but I'm not sure how important that is. I still get a huge pile of failures with it:

```
$ make test_luajit
luajit -l luarocks.loader l2l/test.lua
Starting tests, 1 suite(s)
-- Starting suite "main", 18 test(s)

ERROR in test_extension_alias():
	[string "..."]:2: attempt to index global 'iterator' (a nil value)
stack traceback:
	l2l/test.lua:12: in function 'assert_exec_equal'
	l2l/test.lua:196: in function <l2l/test.lua:195>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50

ERROR in test_iterator():
	./l2l/compiler.lua:84: attempt to call field 'expize' (a nil value)
stack traceback:
	./l2l/compiler.lua:139: in function 'statize'
	./l2l/compiler.lua:400: in function 'compile'
	l2l/test.lua:11: in function 'assert_exec_equal'
	l2l/test.lua:73: in function <l2l/test.lua:72>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50

ERROR in test_cond():
	./l2l/compiler.lua:84: attempt to call field 'expize' (a nil value)
stack traceback:
	[string "local compiler = require("l2l.compiler")..."]:20: in function 'stat_cond'
	[string "local compiler = require("l2l.compiler")..."]:23: in function 'expize'
	./l2l/compiler.lua:84: in function 'expize'
	./l2l/compiler.lua:139: in function 'statize'
	./l2l/compiler.lua:400: in function 'compile'
	l2l/test.lua:11: in function 'assert_exec_equal'
	l2l/test.lua:138: in function <l2l/test.lua:137>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50

ERROR in test_let():
	[string "local vector = require("l2l.vector")..."]:11: attempt to get length of local 'vars' (a nil value)
stack traceback:
	./l2l/reader.lua:382: in function 'expand'
	./l2l/compiler.lua:91: in function 'expize'
	./l2l/compiler.lua:139: in function 'statize'
	./l2l/compiler.lua:400: in function 'compile'
	l2l/test.lua:11: in function 'assert_exec_equal'
	l2l/test.lua:105: in function <l2l/test.lua:104>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50
FAIL: test_backslash (3.09ms): Expected "7", got "nil" (14)
PASS: test_length (1.67ms)
PASS: test_set (1.26ms)
FAIL: test_math (4.53ms): Expected "-1", got "nil" (14)

return {lua={["lua_quote"]={expize=quote.lua.quote.expize,statize=quote.lua.quote.statize,in_lua=true}}}

ERROR in test_lua_quote():
	./l2l/compiler.lua:350: [string "..."]:2: attempt to index global 'quote' (a nil value)
stack traceback:
	./l2l/compiler.lua:350: in function 'import'
	./l2l/reader.lua:324: in function 'import_extension'
	./l2l/reader.lua:346: in function 'dispatch'
	./l2l/reader.lua:361: in function 'macro'
	./l2l/reader.lua:263: in function 'readifnot'
	./l2l/reader.lua:450: in function '(for generator)'
	./l2l/compiler.lua:398: in function 'compile'
	l2l/test.lua:11: in function 'assert_exec_equal'
	l2l/test.lua:97: in function <l2l/test.lua:96>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50

ERROR in test_reduce():
	./l2l/compiler.lua:84: attempt to call field 'expize' (a nil value)
stack traceback:
	./l2l/compiler.lua:139: in function 'statize'
	./l2l/compiler.lua:400: in function 'compile'
	l2l/test.lua:11: in function 'assert_exec_equal'
	l2l/test.lua:89: in function <l2l/test.lua:88>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50
FAIL: test_apply (1.29ms): Expected "3", got "nil" (14)
FAIL: test_fn (1.64ms): Expected "15", got "nil" (14)

ERROR in test_do():
	./l2l/compiler.lua:84: attempt to call field 'expize' (a nil value)
stack traceback:
	[string "local compiler = require("l2l.compiler")..."]:18: in function 'expize'
	./l2l/compiler.lua:84: in function 'expize'
	./l2l/compiler.lua:139: in function 'statize'
	./l2l/compiler.lua:400: in function 'compile'
	l2l/test.lua:11: in function 'assert_exec_equal'
	l2l/test.lua:125: in function <l2l/test.lua:121>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50
PASS: test_and (1.44ms)
PASS: test_infix (1.72ms)
FAIL: test_quasiquote (1.40ms): Expected "list(1, 2, 3)", got "nil" (14)
PASS: test_string (1.07ms)

ERROR in test_local():
	./l2l/compiler.lua:84: attempt to call field 'expize' (a nil value)
stack traceback:
	./l2l/compiler.lua:139: in function 'statize'
	./l2l/compiler.lua:400: in function 'compile'
	l2l/test.lua:11: in function 'assert_exec_equal'
	l2l/test.lua:19: in function <l2l/test.lua:18>
	[C]: in function 'xpcall'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:624: in function 'run_test'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:708: in function 'run_suite'
	/home/phil/.luarocks/share/lua/5.1/lunatest.lua:752: in function 'run'
	l2l/test.lua:204: in main chunk
	[C]: at 0x00404d50
    Finished suite "main", +5 -5 E8 s0

---- Testing finished in 67.31 ms, with 13 assertion(s) ----
  5 passed, 5 failed, 8 error(s), 0 skipped.
Makefile:12: recipe for target 'test_luajit' failed
make: *** [test_luajit] Error 13
```

**Comment by meric** [comment]
I suggest use 5.2 for now and make changes you would like.

I will spend a day on the weekend to figure out 5.1 compatibility - I know ins and outs of everything, it will be straightforward for me.

**Comment by technomancy** [comment]
Unfortunately the tests are failing in 5.2 for me as well: http://p.hagelb.org/l2l-fail-5.2.html

**Comment by meric** [comment]
I've made changes so it will work on 5.1. 
There's been an update to leftry.

```
➜  l2l git:(rewrite) ✗ lua5.1 l2l/test.lua
Starting tests, 1 suite(s)
-- Starting suite "main", 18 test(s)
PASS: test_iterator (0.00ms)
PASS: test_apply (0.00ms)
PASS: test_string (0.00ms)
PASS: test_let (0.00ms)
PASS: test_infix (0.00ms)
PASS: test_and (0.00ms)
PASS: test_lua_quote (0.00ms)
PASS: test_length (0.00ms)
PASS: test_set (0.00ms)
PASS: test_cond (0.00ms)
PASS: test_local (0.00ms)
PASS: test_quasiquote (0.00ms)
PASS: test_backslash (0.00ms)
PASS: test_fn (0.00ms)
PASS: test_extension_alias (0.00ms)
PASS: test_reduce (0.00ms)
PASS: test_math (0.00ms)
PASS: test_do (0.00ms)
    Finished suite "main", +18 -0 E0 s0

---- Testing finished in 0.00 ms, with 39 assertion(s) ----
  18 passed, 0 failed, 0 error(s), 0 skipped.
```

**Comment by meric** [comment]
```
➜  l2l git:(rewrite) ✗ make test_luajit
luajit -l luarocks.loader l2l/test.lua
Starting tests, 1 suite(s)
-- Starting suite "main", 18 test(s)
PASS: test_extension_alias (0.00ms)
PASS: test_iterator (0.00ms)
PASS: test_fn (0.00ms)
PASS: test_let (0.00ms)
PASS: test_backslash (0.00ms)
PASS: test_length (0.00ms)
PASS: test_and (0.00ms)
PASS: test_math (0.00ms)
PASS: test_lua_quote (0.00ms)
PASS: test_reduce (0.00ms)
PASS: test_apply (0.00ms)
PASS: test_cond (0.00ms)
PASS: test_set (0.00ms)
PASS: test_quasiquote (0.00ms)
PASS: test_infix (0.00ms)
PASS: test_string (0.00ms)
PASS: test_do (0.00ms)
PASS: test_local (0.00ms)
    Finished suite "main", +18 -0 E0 s0

---- Testing finished in 0.00 ms, with 39 assertion(s) ----
  18 passed, 0 failed, 0 error(s), 0 skipped.
➜  l2l git:(rewrite) ✗ make test
lua -l luarocks.loader l2l/test.lua
Starting tests, 1 suite(s)
-- Starting suite "main", 18 test(s)
PASS: test_apply (311.25ms)
PASS: test_let (2.31ms)
PASS: test_reduce (5.66ms)
PASS: test_infix (0.92ms)
PASS: test_set (0.85ms)
PASS: test_length (0.97ms)
PASS: test_iterator (31.87ms)
PASS: test_string (1.17ms)
PASS: test_extension_alias (9.62ms)
PASS: test_local (2.11ms)
PASS: test_cond (3.70ms)
PASS: test_do (4.22ms)
PASS: test_lua_quote (5.01ms)
PASS: test_quasiquote (2.02ms)
PASS: test_math (8.17ms)
PASS: test_and (1.04ms)
PASS: test_fn (3.15ms)
PASS: test_backslash (3.68ms)
    Finished suite "main", +18 -0 E0 s0

---- Testing finished in 398.16 ms, with 39 assertion(s) ----
  18 passed, 0 failed, 0 error(s), 0 skipped.
```

**Comment by meric** [comment]
Can you test again? @technomancy

**Comment by technomancy** [comment]
Thanks; I'm down to 4 errors now: http://p.hagelb.org/l2l-test-51-failure.html

Also I noticed that you're using the presence of `_G["loadstring"]` to determine whether you need a custom `ipairs`. I wonder if it wouldn't be better to check by actually attempting to iterate using the existing `ipairs` and seeing if it works as desired. That's what I do here: https://gitlab.com/technomancy/bussard/blob/master/metatable_monkey.lua

**Comment by meric** [comment]
One of the extensions isn't loading properly.

```
ERROR in test_reduce():
    ./l2l/compiler.lua:87: attempt to call field 'expize' (a nil value)
stack traceback:
```

In compiler.lua:87, can you add a print statement to print `car[1]`?

Then we can know which extension these errors are related to and look there.

```
if utils.hasmetatable(car, symbol) and invariant.lua[car[1]] then
      -- PRINT car[1] HERE.
      data, expanded = reader.expand(invariant,
        invariant.lua[car[1]].expize(invariant, data:cdr(), output))
      if expanded then
        return expize(invariant, data, output)
      else
        return data
      end
    end
```

**Comment by meric** [comment]
https://github.com/meric/leftry/commit/1c3c3242809a43821b4b518fe623a72a912b8130

Updated leftry to feature test instead of looking at loadstring.

**Comment by technomancy** [comment]
Sure thing: http://p.hagelb.org/l2l-test-luajit-failure.html

**Comment by meric** [comment]
[ext.zip](https://github.com/meric/l2l/files/465365/ext.zip)

@technomancy Can you compare the .lua files compiled from my end to the ones compiled on your end, and see if there are major differences?

Or you can upload yours too and I can inspect them.

**Comment by meric** [comment]
Also, just making sure, do you run `make clean` on each test iteration?

**Comment by technomancy** [comment]
Oh; didn't realize `make clean` was necessary; I thought it would check timestamps and stuff. That did the trick; thanks!

**Comment by meric** [comment]
Ha! It checks the hash of the input file rather than timestamp. The .lua outputs were generated by buggy version of the compiler while the input file remained unchanged, so the outputs were buggy too, until `make clean` was called.

**Comment by meric** [comment]
Thanks for submitting this issue, now l2l is Lua 5.1, 5.2 ,5.3, LuaJit compatible.

**Comment by technomancy** [comment]
Lovely. What is remaining on the list for merging the rewrite branch into master?

**Comment by meric** [comment]
Hmm. The only iterations possible in lisp are: reduce, map, filter. Otherwise must escape into Lua to use for,while,repeat.

The `and` and `or` does not currently short circuit properly, especially if it's like a (and (cond ...) (cond ...)) All the cond's will be executed first before the and condition is evaluated. It does something like:

``` if x then x1=true end; if y then y1=true end; z = x1 and y1```

Do you think these shortcomings aren't enough of an issue to merge rewrite into master?

And one final point is to write the documentation, do a REPL, implement a command to run an arbitrary l2l script.

**Comment by technomancy** [comment]
I think adding an `each` that works like `map` but does not accumulate a return value would be good enough on the iterator front. (I might be able to tackle this.) Missing the short-circuiting seems like a more serious blocker.

Probably the repl, bin script, and docs can wait till after the merge. My vote would be to prioritize the documentation in order to make it easier for others to contribute stuff like the repl and bin script. =)

**Comment by technomancy** [comment]
I'm looking at the implementation of `map` in `iterator.lisp` and it looks like `map` builds up a function whether it's being compiled to an expression or to a statement. Is that a bug? Seems like it should discard the value and act like `each` if it's compiling to a statement, right?

**Comment by meric** [comment]
That's a good observation. Yes, it ought to work like an each when it's in statement. :) I would be all too happy for you to work on that file and change it however you please. 

I'll work on the short-circuiting next.

**Comment by technomancy** [comment]
I'll take a crack at it. It would be helpful to get an overview of what some of the terms mean though. You've already described `statize` and `expize`, but what does `invariant` mean?

It seems like `compile_map` can behave differently whether the thing its iterating over has `lua_iteration` as its metatable, but what does this mean practically speaking?

What is the `block` field of an iterable used for?

What does it mean for functions like `:unpack` to start with a colon?

thanks.

**Comment by meric** [comment]
invariant is the environment. It's a table containing the source code, the read macro table, the lua special form table, the macro table, the dispatch macro table, (refer to `reader.environ`).

I could call it "environment", but I called it invariant, because the way the `reader.read` function is written, we can use `reader.read` and `invariant` terms directly in the for-loop.

```
for rest, values in reader.read, invariant do
    for _, value in ipairs(values) do
      table.insert(output, statize(invariant, value, output, rest > length))
    end
    ending = rest
  end
```

In Lua, the `for .. in ..` loop, on the right side after `in`, it can take 3 terms. The first term is the iterator function. The second term is customarily called the `invariant`, and the third term the control variable.

See https://www.lua.org/pil/7.2.html.

```
Actually, it keeps three values: The iterator function, an invariant state, and a control variable. Let us see the details now.
```

**Comment by meric** [comment]
> It seems like compile_map can behave differently whether the thing its iterating over has lua_iteration as its metatable, but what does this mean practically speaking?

Let's take an example:

```
@import iterator
\
map(function(x) return x + 2 end,
  filter(function(x) return x % 2 == 0 end,
    map(function(x) return x + 1 end, {1, 2, 3, 4})))
```

compiles to:

```
local vector = require("l2l.vector")
local ipairs = require("l2l.iterator")
local next6,invariant5,i7 = ipairs({1,2,3,4});local values9 = vector();while i7 do local v8;i7,v8=next6(invariant5,i7);if i7 then v8=v8 + 1;if v8 % 2 == 0 then v8=v8 + 2;(values9):insert(v8) end end end
return values9
```

These are special forms used in Lua. Note the anonymous functions converted into inline macros.

The plain table array `{1, 2, 3, 4}`, is wrapped in a `map` call, wrapped in a `filter` call, wrapped in a `map` call. Before the `map` call, there's no `lua_iteration`. So the first `map` call detects this, and must initialise a `lua_iteration`. The latter calls receive `lua_iteration` as the argument, and do not need to initialise one.

> What is the block field of an iterable used for?

The `block` field is a more or less a function that generates the source code, quoted above, using the properties of the lua_iteration object. 

Why `lua_iteration`? Why not just make simple map, filter, reduce functions? The reason is, plain `map` and plain `filter` functions causes nested for-loops and function calls. `lua_iteration` allows us to stack lots of `map` and `filter` and finally, possibly a `reduce`, so as to collapse it all into a single loop, and the `compiler.macroize`, which converts some anonymous functions into an inline-macro, we reduce the number of function calls as well. This ought to significantly enhance performance on LuaJIT and Lua itself. 

Computer games require a lot of loops, and when I was using Lua, I realised writing map, filter functions was excessively inefficient, and I had to hand optimise those loops by hand, but it was cumbersome, due the the function call abstractions and lots of nested loops. It was from this observation that led to the implementation of the current `l2l` and `iterator.lisp`.

> What does it mean for functions like :unpack to start with a colon?

`(:unpack cdr ...)` is equivalent to `cdr:unpack(...)`.

It's a special quirk in this lisp.

**Comment by technomancy** [comment]
So would it be correct to sum up `lua_iterator` by saying that it's a way to collapse nested iterations into a single pass? That's a really cool feature, even if it is a bit tricky to follow the code for it.

Thanks for the explanation.

**Comment by meric** [comment]
Yes, that's what it does. Thanks.

**Comment by meric** [comment]
If you can think of a better abstraction, great! It was something I came up with over a few hours.

**Comment by technomancy** [comment]
So it seems like `compile_map` needs to have an arg which tells it whether to accumulate or discard the list elements, and `statize_each` and `expize_each` can use `compile_map` with that arg set to true, as will `statize_map`.

Looking at it further, I'm afraid while I conceptually understand the difference between statizing and expizing, I don't understand the relationship between the `output` argument and the return value in the two cases. In `expize_map`, the `iterable.block` table is inserted into `output`, while in `statize_map` it is simply returned by the `create` function. Having an `output` table that you shove things into seems conceptually the same thing as returning values. What's the difference?

**Comment by meric** [comment]
The `return` value returns a lua expression that can be slotted in where lua expressions are expected.

But sometimes we want to add some statements, e.g. a while loop, and that can't be a lua expression (unless wrapped in an anonymous function call, which is slow), then we just chuck stuff into output, and in the statements, assign whatever we want to some variable, and return that variable instead. The stuff we put inside output will be executed before the reference to the return is used.

**Comment by meric** [comment]
E.g. in the expression `(+ (reduce +  {1, 2, 3, 4}) 1)`, reduce needs to insert some lua loop statements into `output`. It can't just embed the loop like `for i, v in ipairs({1, 2, 3, 4} do return ... end + 1`, which does not work. It puts the loop into `output`, reduces over some variable, and that variable is inserted like `reduction +1 `, where `reduction` is the variable that stores the sum.

**Comment by meric** [comment]
`statize` always return some statement, for the parent block to accumulate.

**Comment by technomancy** [comment]
I'm sorry; I think I will need a simpler place to start than the iterator code. It's just too twisty and undocumented for me to make sense of what it needs to do, despite your help here. TBH having an `each` is really not important enough to be a blocker for merging to master.

I could probably do better adding a bin script or a repl instead.

**Comment by meric** [comment]
@technomancy Yes. It's fine as it is, and could probably do with knocking it down and rewriting it one day, but it doesn't have to be before the branch is merged.

**Comment by meric** [comment]
Short-circuiting  for `and` and `or` is implemented. I've merged rewrite into master branch, and tagged the old master 'legacy'

**Comment by technomancy** [comment]
Glad to hear it! Nice work.
