### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by meric** [meric/l2l#48]
In the case of syntax error in the lisp source, we want to show pretty exception messages.

When compiling Lisp in debug mode, and there are run time errors, we want to show a traceback in Lisp, in addition to the traceback of the compiled Lua.

**Comment by technomancy** [comment]
I appreciate that l2l compiles to lua source, but I read somewhere that compiling directly to bytecode is the only way to get stack traces with correct line numbers. Is that something you've looked into?

**Comment by meric** [comment]
Hmm. My original intention was to use static analysis to wrap all function calls with pcall. I'm not sure compiling to byte code is feasible because then we'd have to re-implement all the ext/ features to compile to byte code as well as Lua.

**Comment by technomancy** [comment]
Yeah, I agree that compiling to bytecode is not ideal; I guess I'm asking more if you have any other solution to the problem of line numbers.

My understanding is that while an individual pcall isn't a big deal, introducing them everywhere would result in a pretty serious slowdown, but I haven't tested this.

What did you mean by using static analysis to add in pcall?

**Comment by technomancy** [comment]
Oh, you mean using pcall to catch exceptions and then emitting your own error messages that have line numbers in the right place. Hmm.

I wonder if you could write your own pcall variant or debug.traceback variant that could inspect metatables on functions and somehow use those to produce sensible stack traces.

**Comment by meric** [comment]
I'm going to find some time to experiment with it a bit. I'm hopeful we can build a solid solution - we have the parser combinator, the Lua syntax trees.

**Comment by meric** [comment]
Here's a first cut.... No traceback.

Added a argument to compiler.compile to turn on debug mode which would wrap function calls in `trace` which prints pretty error messages.

```
./l2l/trace.lua:9: ERROR: attempt to perform arithmetic on a nil value
Module "test". Line 3, column 15:
1	|(let (x 1
2	|            y 2
3	|            z 3 + nil) z)
	|~~~~~~~~~~~~~~^^^^^^^~~~~
```

**Comment by meric** [comment]
Traceback implemented... :)

```
ERROR: attempt to perform arithmetic on a nil value (upvalue 'u')
Module "test". Line 4, column 15:
3	|            y 2
4	|            z 3 + u) z))
	|~~~~~~~~~~~~~~^^^^^~~~~~
5	|      (print (q nil))
Module "test". Line 5, column 14:
4	|            z 3 + u) z))
5	|      (print (q nil))
	|~~~~~~~~~~~~~^^^^^^^~
6	|      (print 1)
```

**Comment by technomancy** [comment]
Very cool. But I had no idea there was infix arithmetic; odd.

I have integrated l2l into Liko-12, a low-fi game dev environment built with love2d: https://github.com/technomancy/LIKO-12/tree/lisp

**Comment by meric** [comment]
Thanks, the infix arithmetic is because numbers are also an entry point to Lua. (besides \ and {)
