### ISSUE TITLE
Wrong compilation for cond+not inside quasiquote

### ISSUE THREAD

**Issue by carloscm** [meric/l2l#55]
I'm using the line-numbers-in-comments branch.

Given this input to the l2l compiler:
```lisp
(local v 1)
(local r nil)

(cond
    (not v) (set r "a")
    (set r "b"))
(print r)
```
A correct compilation is created:
```lua
local v = 1

local r = nil

local _cond_value0

local _cond_found1

if  not v then _cond_found1=true
do end
r="a"
do end
_cond_value0=r
else

end

if  not _cond_found1 then r="b"
do end
_cond_value0=r
end
print(r)
```
But if we put the cond body inside a high level macro using a quasiquote and some escapes:
```lisp
-- save as sm_macros.lisp
@import fn
@import quasiquote

(fn test_qq (vn rn)
    `(cond
        (not ,vn) (set ,rn "a")
        (set ,rn "b")))

{
    macro = {
        ["test_qq"] = test_qq,
    }
}
```
And run the code as:
```lisp
@import sm_macros

(local v 1)
(local r nil)

(test_qq v r)
(print r)
```
Then the compilation output is nonsensical:
```lua
local v = 1

local r = nil

local _var0 = "b"
print(r)
```
If "not" is not present in the cond, it appears to create a correct output.
Here I replaced "(not ,vn)" with ",vn" in the macro:
```lua
local v = 1

local r = nil

local _cond_value11

local _cond_found12

if v then _cond_found12=true
do end
r="a"
do end
_cond_value11=r
else

end

if  not _cond_found12 then r="b"
do end
_cond_value11=r
end
print(r)
```

**Comment by meric** [comment]
I'm going to look at it these few days.

**Comment by meric** [comment]
I saved sm_macros.lisp into ext/ folder and tried your example but it seems ok to me.

```
➜  l2l git:(line-number-in-comments) ✗ lua5.1  whatt.lua


local v = 1

local r = nil

local _cond_value54

local _cond_found55

if  not v then _cond_found55=true
do end
r="a"
do end
_cond_value54=r
else

end

if  not _cond_found55 then r="b"
do end
_cond_value54=r
end

return print(r)
➜  l2l git:(line-number-in-comments) ✗ cat whatt.lua    
local compiler = require"l2l.compiler"
local src = compiler.compile(
[[

@import sm_macros

(local v 1)
(local r nil)

(test_qq v r)
(print r)


]]

  , "test", false)
print (src)
```

Can you try `make clean` and run it again?

**Comment by meric** [comment]
```
➜  l2l git:(line-number-in-comments) ✗ cat l2l/ext/sm_macros.lisp 
-- save as sm_macros.lisp
@import fn
@import quasiquote

(fn test_qq (vn rn)
    `(cond
        (not ,vn) (set ,rn "a")
        (set ,rn "b")))

{
    macro = {
        ["test_qq"] = test_qq,
    }
}
➜  l2l git:(line-number-in-comments) ✗ cat l2l/ext/sm_macros.lua           
--138895.9
local list = require("l2l.list");
local lua = require("l2l.lua");
local lua_string = lua.lua_string
local reader = require("l2l.reader");
local symbol = reader.symbol

local function test_qq(vn,rn)
return list(symbol("cond"), list(symbol("not"), vn), list(symbol("set"), rn, lua_string("a")), list(symbol("set"), rn, lua_string("b")))
end

return {macro={["test_qq"]=test_qq}}%    
```

**Comment by carloscm** [comment]
Okay, if the macros_sm.lisp file is located inside l2l/ext, it works.
If it's located in other folder (for example, in the l2l root), then the wrong compilation happens.
The generated lua code is also different depending on the folder. Here's sm_macros.lua when sm_macros.lisp is inside ext:
```lua
--138696.3
local list = require("l2l.list");
local lua = require("l2l.lua");
local lua_string = lua.lua_string
local reader = require("l2l.reader");
local symbol = reader.symbol

local function test_qq(vn,rn)
return list(symbol("cond"), list(symbol("not"), vn), list(symbol("set"), rn, lua_string("a")), list(symbol("set"), rn, lua_string("b")))
end

return {macro={["test_qq"]=test_qq}}
```
Here's sm_macros.lua when sm_macros.lisp is outside ext:
```lua
--138696.3
local lua = require("l2l.lua");
local lua_string = lua.lua_string

local function test_qq(vn,rn)
local _cond_value54
do end

local _cond_found55
do end

if  not vn then _cond_found55=true
do end
rn=lua_string("a")
do end
_cond_value54=rn
else

end
do end

if  not _cond_found55 then rn=lua_string("b")
do end
_cond_value54=rn
end
do end

return _cond_value54
end

return {macro={["test_qq"]=test_qq}}
```
Apparently quasiquote only works when the file is inside ext? Am I missing some import?
The reason I'm trying to define macros outside ext is because I want to be able to support app or user provide macros, not just those provided as a l2l language macro. The ones I'm porting now are too app-specific to be part of the l2l distribution.

**Comment by carloscm** [comment]
One more data point: if the file is kept outside of the ext folder, and (not ,vn) is replaced by something like \not(false), then the correct code is generated. Looks like some super weird interaction between lisp-side not, quasiquote, cond and being outside ext/.

**Comment by meric** [comment]
Yes it looks like some search path related bug...

**Comment by meric** [comment]
@carloscm I've made a commit that seems to fix the issue and pass the tests. It looks like attempt to macroexpand the forms returned from special forms was causing the bug, and that's been removed. The returned form from special forms is no longer macroexpanded; (it can be done manually within the special form function).i.e. Quasiquote should not have its contents macroexpanded.

It worked in ext/ because all extensions in ext/ had a special rule where all special forms must be explicitly imported, and that example was missing the *not* macro because ext/operators wasn't being imported, and so there was no macro expansion from quasiquote because there was no macros in the return.

**Comment by carloscm** [comment]
Indeed the compilation of both the macro expander and the code is correct, but now I'm getting errors from the compiler while trying to load and compile code, from operators.lua, line 38:
```lua
if  not a"" then _cond_value0=...
```
Error dump:
```
...MiniSuit\Resources\core/system/lib/l2l\ext\operators.lua:38: attempt to call local 'a' (a table value)
stack traceback:
    ...MiniSuit\Resources\core/system/lib/l2l\ext\operators.lua:38: in function <...MiniSuit\Resources\core/system/lib/l2l\ext\operators.lua:34>
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\reader.lua:466: in function 'expand'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\reader.lua:458: in function 'f'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\vector.lua:92: in function 'cast'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\reader.lua:467: in function 'expand'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\reader.lua:458: in function 'f'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\vector.lua:92: in function 'cast'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\reader.lua:467: in function 'expand'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\reader.lua:458: in function 'f'
    ...projects\MiniSuit\Resources\core/system/lib/l2l\list.lua:175: in function 'cast'
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\reader.lua:469: in function 'expand'
    ...
    ...ojects\MiniSuit\Resources\core/system/lib/l2l\ext\fn.lua:58: in function 'f'
    ...ojects\MiniSuit\Resources\core/system/lib/leftry\ast.lua:302: in function 'gsub'
    ...ojects\MiniSuit\Resources\core/system/lib/leftry\ast.lua:61: in function 'gsub'
    ...ojects\MiniSuit\Resources\core/system/lib/leftry\ast.lua:304: in function 'gsub'
    ...ects\MiniSuit\Resources\core/system/lib/l2l\compiler.lua:65: in function 'statize'
    ...ects\MiniSuit\Resources\core/system/lib/l2l\compiler.lua:516: in function 'compile'
    ...uit\projects\MiniSuit\Resources\core/system/lib/base.lua:173: in function 'custom_compile_or_cached'
    ...uit\projects\MiniSuit\Resources\core/system/lib/base.lua:203: in function 'include_lisp'
    ...inisuit\projects\MiniSuit\Resources\core/system/main.lua:8: in function 'include_lua_abs'
    ...uit\projects\MiniSuit\Resources\core/system/lib/base.lua:24: in function <...uit\projects\MiniSuit\Resources\core/system/lib/base.lua:18>
```
It's the `not a""` code, which in the lisp a quoted lua not:
```lisp
(fn .. (a ...)
  (cond
    \not a ""
```

**Comment by meric** [comment]
I think that's a separate issue, I've pushed a fix. The parser thinks `\not a ""` means `\not a""` (which is Lua's alternative function calling syntax where there is a single string argument). I added a semicolon `\not a; ""` which fixed the issue.

**Comment by carloscm** [comment]
Ah, I see now. I believed it was related to the change because I didn't see this error before, but I also forgot my transpiler has begun to translate `append-string` into `..` so this triggered at the same time. All is good now and the issue can be closed.

I'm now loading and compiling more than 50% of the transpiled 37KLOCs, the non-loading rest are all my fault and I'm working on it. Actually running it will be a very different matter :)

I see you landed the line numbers branch, are you back in master?

**Comment by meric** [comment]
Ok. that sounds great! hopefully it go all smoothly. Yes I've merged line-numbers branch to master since it's got the two important fixes.
