### ISSUE TITLE
Infix arithmetic is sometimes not desired

### ISSUE THREAD

**Issue by carloscm** [meric/l2l#60]
For example, I want to call a two argument function like `(2d-point 0.2 -0.2)`. In the REPL:
```
> (list 0.2 -0.2)
list(0)
```
Some way to toggle this behavior by the compiler would be necessary. It can also generate invalid code like:
```
> (list "a" -2)
ERROR: attempt to perform arithmetic on a string value
```
Right now I need to write all negative number constants as (- n) to avoid this behavior.

**Comment by meric** [comment]
Ok hopefully this fixes it fa0f216fb4314060f498a1c1518f570cc95114e3

**Comment by carloscm** [comment]
I confirm it fixes the problem, thanks!

**Comment by carloscm** [comment]
Well this is the gift that keeps on giving. Now:
```
(list {"a","b"} -1)
```
Again tries to translate into a substraction. This time I guess it's because of the table being used with Lua syntax, since this one works (and keeping in mind the tables are not same, I know, but not relevant to the bug):
```
(list {"a" "b"} -1)
```
I would suggest to not disable Lua mode for table contents since it's very valuable feature to have (destructuring let, easy raw indexed tables, etc) and I'm happy to just escape this one out.

**Comment by meric** [comment]
I'll fix this by making it a read_lua_table instead of read_lua_literal...coming soon.
