### ISSUE TITLE
seti

### ISSUE THREAD

**Issue by ghost** [meric/l2l#63]
'seti' works fine in REPL, but it does not work in script:
```
(set x '(0 2 3 4))
(seti x 1 1)

lua: /usr/local/share/lua/5.1/l2l/main.lua:117: attempt to call a nil value
stack traceback:
	/usr/local/share/lua/5.1/l2l/main.lua:117: in function 'run'
	/usr/local/bin/l2l:3: in main chunk
	[C]: at 0x563c6c5731d0
```

--_tested with "l2l version 0.0.2-pre" on Linux - Pepermint 9 [x86_64]_

**Comment by ghost** [comment]
Sorry ! It works in script, but only in a 'let' or 'do' block':

```
(let (x '(0 2 3 4))
  (print x)      --> list(0, 2, 3, 4)
  (seti x 1 1)
  (print x))     --> list(1, 2, 3, 4)
```

**Comment by meric** [comment]
Ok. How can I help? What do you suggest?

**Comment by ghost** [comment]
I just wondered why 'seti' didn't perform likewise in a REPL and in a script. Maybe scopes are managed differently in both of them. I think the important thing is to be aware of it and to understand the reason(s) of this feature... Sorry for the upset, but I just discovered 'l2l' recently, beside Urn and Fennel, and I am exploring it with interest rather as a hobby...

**Comment by meric** [comment]
Hi - the project currently has a lot of basic functionality, but it could
use a lot more polish. I was working on a new version and have dropped it
for the last year or so due to a lack of time. Feel free to take a look,
hopefully one day when I get a bit ahead at work and family I’ll be able to
revisit the project.

**Comment by ghost** [comment]
Thank you for your answers... I'll do carry on with my exploration of l2l, being carefull of possible evolutions, because I like the "practical philosophy" of l2l...
